repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        types_or: [c, c++]
# - repo: local

#   hooks:
#   - id: clang-tidy
#     name: clang-tidy
#     language: docker_image
#     entry: https://github.com/cpp-linter/clang-tools-docker:latest
#   - id: dbt-format
#     name: dbt-format
#     entry: ./dbt.py format -g
#     language: script
