repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  # - repo: local
  #   hooks:
  #     - id: dbt-format
  #       name: dbt-format
  #       entry: ./dbt format -g
  #       language: script
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
    - id: clang-format
      types_or: [c, c++]
